"""
Flask RSS Cleaning Proxy for Nitter/Twitter feeds
Optimized for Telegram RSS bots — supports both RSStT and simple bots.

Endpoints:
  GET /clean?url=<rss_url>[&format=html|text]
      format=html  (DEFAULT) keeps HTML for RSStT
      format=text  strips HTML to plain text for simple bots

  GET /clean-all?urls=url1,url2,…[&format=html|text]
  GET /health
  GET /

Deploy with:  gunicorn -c gunicorn.conf.py app:app
"""

import re
import time
import hashlib
import logging
from datetime import datetime, timezone
from urllib.parse import urljoin, urlparse
from xml.sax.saxutils import escape

import feedparser
import requests
from bs4 import BeautifulSoup, NavigableString
from flask import Flask, request, Response, jsonify

# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
MAX_ITEMS     = 20
CACHE_TTL     = 300
MAX_TEXT_LEN  = 1200
FETCH_TIMEOUT = 10

#ALLOWED_FEED_URLS: set[str] = set()
ALLOWED_FEED_URLS: set[str] = {
    "https://nitter.net/elonmusk/rss",
    "https://nitter.net/sama/rss",
    "https://nitter.privacydev.net/elonmusk/rss",
    "https://nitter.privacydev.net/sama/rss",
    "https://nitter.net/IPRDBihar/rss",
    # Add more as needed…
}

ALLOWED_DOMAINS: set[str] = {
    "nitter.net", "nitter.privacydev.net", "nitter.poast.org",
    "xcancel.com", "nitter.cz", "nitter.1d4.us", "nitter.kavin.rocks",
    "nitter.unixfox.eu", "nitter.42l.fr", "twitt.re", "nitter.pek.li",
}

IGNORED_IMAGE_RE = re.compile(
    r"(avatar|profile_images|icon|logo|emoji|favicon|badge|default_profile)",
    re.IGNORECASE,
)

# Matches any Nitter status URL → used to rewrite to x.com
_NITTER_STATUS_RE = re.compile(
    r"https?://[^/]+/([^/]+)/status/(\d+)(?:#m)?",
    re.IGNORECASE,
)

# ─────────────────────────────────────────────────────────────────────────────
# Cache
# ─────────────────────────────────────────────────────────────────────────────
_cache: dict[str, tuple[float, str]] = {}

def cache_get(key: str) -> str | None:
    entry = _cache.get(key)
    if entry and (time.time() - entry[0]) < CACHE_TTL:
        return entry[1]
    _cache.pop(key, None)
    return None

def cache_set(key: str, value: str) -> None:
    _cache[key] = (time.time(), value)

# ─────────────────────────────────────────────────────────────────────────────
# Security
# ─────────────────────────────────────────────────────────────────────────────
_PRIVATE_PREFIXES = ("localhost", "127.", "10.", "192.168.", "172.", "0.0.0.0")

def is_url_allowed(url: str) -> bool:
    if not url:
        return False
    try:
        parsed = urlparse(url)
    except Exception:
        return False
    if parsed.scheme not in ("http", "https"):
        return False
    host = (parsed.hostname or "").lower()
    if not host or any(host.startswith(p) for p in _PRIVATE_PREFIXES):
        return False
    return url in ALLOWED_FEED_URLS or host in ALLOWED_DOMAINS

# ─────────────────────────────────────────────────────────────────────────────
# Small helpers
# ─────────────────────────────────────────────────────────────────────────────

def nitter_url_to_xcom(href: str) -> str:
    """Convert a Nitter status URL to x.com. Non-status URLs unchanged."""
    m = _NITTER_STATUS_RE.match(href)
    if m:
        return f"https://x.com/{m.group(1)}/status/{m.group(2)}"
    return href

def nitter_search_to_xcom(href: str) -> str:
    """
    Convert a Nitter hashtag search URL to an x.com search URL.
    https://nitter.net/search?f=tweets&q=%23Bihar
    → https://x.com/search?f=tweets&q=%23Bihar
    """
    if "nitter" in href and "/search" in href:
        # Replace the host part, keep everything from /search onward
        parsed = urlparse(href)
        return f"https://x.com{parsed.path}?{parsed.query}" if parsed.query else f"https://x.com{parsed.path}"
    return href

def strip_username_from_author(author: str) -> str:
    """'Nitish Kumar (@NitishKumar)' → 'Nitish Kumar'"""
    author = re.sub(r"\s*\(@\w+\)\s*$", "", author).strip()
    author = re.sub(r"\s*@\w+\s*$",     "", author).strip()
    return author

def clean_feed_description(desc: str) -> str:
    """Remove 'Generated by https://nitter.net' suffix from channel description."""
    if not desc:
        return desc
    desc = re.sub(r"\.\s*Generated by\s+https?://\S+", "", desc, flags=re.IGNORECASE)
    desc = re.sub(r"\s*Generated by\s+https?://\S+",   "", desc, flags=re.IGNORECASE)
    return desc.strip()

# ─────────────────────────────────────────────────────────────────────────────
# Core helper — identify and remove the trailing mention/hashtag block
# ─────────────────────────────────────────────────────────────────────────────

def _is_mention_or_hashtag_link(tag) -> bool:
    """Return True if this <a> tag is a @mention or #hashtag link."""
    if tag.name != "a":
        return False
    href = tag.get("href", "")
    text = tag.get_text(strip=True)
    # Hashtag: href contains %23 or starts with /search
    if "%23" in href or href.startswith("/search"):
        return True
    # @mention: text starts with @
    if text.startswith("@"):
        return True
    return False

def _node_is_only_whitespace_or_br(node) -> bool:
    """True if a NavigableString is blank, or a <br> tag."""
    if isinstance(node, NavigableString):
        return node.strip() == ""
    return getattr(node, "name", None) == "br"

def _remove_trailing_tag_block_from_p(p_tag, mode: str) -> None:
    """
    Walk the children of a <p> tag from the END backwards.
    Remove any trailing <br> separators and @mention / #hashtag <a> tags
    that form the footer block Nitter appends to every tweet.

    In HTML mode: hashtag <a> tags are converted to x.com links (kept).
                  @mention <a> tags are replaced with full name.
    In TEXT mode: both are removed entirely.

    We stop as soon as we hit real text content.
    """
    children = list(p_tag.children)

    # Walk backwards, collecting the trailing junk nodes
    trailing_indices = []
    for i in range(len(children) - 1, -1, -1):
        node = children[i]
        if _node_is_only_whitespace_or_br(node):
            trailing_indices.append(i)
            continue
        if isinstance(node, NavigableString):
            # Real text — stop
            break
        if node.name == "a":
            if _is_mention_or_hashtag_link(node):
                trailing_indices.append(i)
                continue
        # Anything else — stop
        break

    if not trailing_indices:
        return

    # Now process each trailing node
    for i in sorted(trailing_indices, reverse=True):
        node = children[i]
        if isinstance(node, NavigableString) or getattr(node, "name", None) == "br":
            node.extract()
            continue

        if node.name == "a":
            href = node.get("href", "")
            text = node.get_text(strip=True)
            is_hashtag = "%23" in href or href.startswith("/search")
            is_mention = text.startswith("@")

            if mode == "html":
                if is_hashtag:
                    # Convert to x.com search link, keep as clickable link
                    new_href = nitter_search_to_xcom(href)
                    node["href"] = new_href
                    # Keep the tag — don't remove it
                    # But DO remove it from trailing_indices so it stays
                    # We still want to trim the surrounding <br> separators though
                    # Restore it — don't extract
                    continue
                elif is_mention:
                    # Replace with full name text
                    full_name = (node.get("title") or "").strip()
                    if full_name:
                        node.replace_with(full_name)
                    else:
                        node.unwrap()
            else:
                # TEXT mode — remove both hashtags and mentions entirely
                node.extract()


def _process_p_tags(soup, mode: str) -> None:
    """
    For every <p> in the soup (but NOT inside <blockquote>):
    remove the trailing @mention + #hashtag block.
    Blockquotes are handled separately.
    """
    for p in soup.find_all("p"):
        # Skip <p> tags inside a blockquote — those are quoted content
        if p.find_parent("blockquote"):
            continue
        _remove_trailing_tag_block_from_p(p, mode)

# ─────────────────────────────────────────────────────────────────────────────
# Feed fetching
# ─────────────────────────────────────────────────────────────────────────────

def fetch_feed(url: str) -> feedparser.FeedParserDict | None:
    try:
        resp = requests.get(url, timeout=FETCH_TIMEOUT,
                            headers={"User-Agent": "Mozilla/5.0 (compatible; RSSProxy/1.0)"})
        resp.raise_for_status()
        feed = feedparser.parse(resp.content)
        if feed.bozo and not feed.entries:
            log.warning("feedparser bozo for %s: %s", url, feed.bozo_exception)
            return None
        return feed
    except requests.Timeout:
        log.error("Timeout fetching %s", url)
    except requests.RequestException as exc:
        log.error("HTTP error for %s: %s", url, exc)
    return None

# ─────────────────────────────────────────────────────────────────────────────
# HTML MODE — clean_html()
# ─────────────────────────────────────────────────────────────────────────────

def clean_html(html: str, base_url: str = "") -> str:
    """
    Clean Nitter HTML for RSStT consumption.

    1. <footer> / <cite>       → removed
    2. <hr/>                   → removed
    3. <img> URLs              → absolute, avatars removed, styles stripped
    4. Trailing @mention links → replaced with full name (title= attribute)
    5. Trailing #hashtag links → href rewritten to x.com search URL (kept as links)
    6. Inline (non-trailing) @mention / #hashtag links → kept as-is
       (they are part of real sentence content — not stripped)
    7. Blockquote author <b>   → (@username) stripped
    8. Video anchor hrefs      → Nitter status URL → x.com
    """
    if not html:
        return ""

    soup = BeautifulSoup(html, "html.parser")

    # 1. Remove <footer> and <cite>
    for tag in soup.find_all(["footer", "cite"]):
        tag.decompose()

    # 2. Remove <hr/>
    for hr in soup.find_all("hr"):
        hr.decompose()

    # 3. Fix <img> URLs
    for img in soup.find_all("img"):
        src = (img.get("data-src") or img.get("src") or "").strip()
        if not src:
            img.decompose()
            continue
        if src.startswith("//"):
            src = "https:" + src
        elif not src.startswith("http") and base_url:
            src = urljoin(base_url, src)
        if IGNORED_IMAGE_RE.search(src):
            img.decompose()
            continue
        img.attrs = {"src": src}

    # 4 & 5. Remove/rewrite trailing mention+hashtag block from each <p>
    _process_p_tags(soup, mode="html")

    # 6. For any remaining <a> tags (not already handled above):
    for a in soup.find_all("a", href=True):
        href = a.get("href", "")
        text = a.get_text(strip=True)

        # Remaining @mention links (inline in content) → replace with full name
        if text.startswith("@"):
            full_name = (a.get("title") or "").strip()
            a.replace_with(full_name if full_name else text)
            continue

        # Video / status anchor → convert href to x.com
        converted = nitter_url_to_xcom(href)
        if converted != href:
            a["href"] = converted

    # 7. Strip (@username) from blockquote author <b> tags
    for bq in soup.find_all("blockquote"):
        b_tag = bq.find("b")
        if b_tag:
            b_tag.string = strip_username_from_author(b_tag.get_text(strip=True))

    return str(soup)


# ─────────────────────────────────────────────────────────────────────────────
# TEXT MODE — html_to_text() + clean_text()
# ─────────────────────────────────────────────────────────────────────────────

def html_to_text(html: str) -> str:
    """
    Convert Nitter HTML to clean plain text.
    - Trailing @mention / #hashtag block removed per <p>
    - Inline mentions replaced with full name
    - Blockquote author (@username) stripped
    - Video anchors → ▶ Video: https://x.com/…
    """
    if not html:
        return ""

    soup = BeautifulSoup(html, "html.parser")

    # 1. Remove <footer> and <cite>
    for tag in soup.find_all(["footer", "cite"]):
        tag.decompose()

    # 2. Remove all <img> tags
    for img in soup.find_all("img"):
        img.decompose()

    # 3. Remove trailing mention+hashtag block from each <p>
    _process_p_tags(soup, mode="text")

    # 4. Handle remaining <a> tags
    for a_tag in soup.find_all("a", href=True):
        href      = a_tag.get("href", "")
        text      = a_tag.get_text(strip=True)
        full_name = (a_tag.get("title") or "").strip()

        # Video anchor → ▶ Video: x.com URL
        if "video" in text.lower() and not text.startswith("@"):
            xcom_url = nitter_url_to_xcom(href)
            a_tag.replace_with(f"\n▶ Video: {xcom_url}\n")
            continue

        # Remaining @mention → full name or bare handle
        if text.startswith("@"):
            a_tag.replace_with(full_name if full_name else text)
            continue

        # Inline hashtag link — unwrap to keep the #tag text in place
        if text.startswith('#'):
            a_tag.unwrap()
            continue

        # Everything else → unwrap (keep text)
        a_tag.unwrap()

    # 5. Replace <hr/> with visual divider
    for hr in soup.find_all("hr"):
        hr.replace_with("\n" + "─" * 16 + "\n")

    # 6. Format <blockquote> with clean author label
    for bq in soup.find_all("blockquote"):
        author_tag = bq.find("b")
        if author_tag:
            author_name = strip_username_from_author(author_tag.get_text(strip=True))
            author_tag.decompose()
        else:
            author_name = ""

        for inner in bq.find_all(["p", "br", "div"]):
            inner.insert_before("\n")
            inner.insert_after("\n")

        bq_text = bq.get_text(separator="", strip=False)
        bq_text = re.sub(r"\n{3,}", "\n\n", bq_text).strip()

        quoted_block = f"\n\n💬 {author_name}\n{bq_text}\n" if author_name else (
            f"\n\n💬\n{bq_text}\n" if bq_text else ""
        )
        bq.replace_with(quoted_block)

    # 7. Insert newlines at block-level tags
    for tag in soup.find_all(["p", "br", "div", "li"]):
        tag.insert_before("\n")
        tag.insert_after("\n")

    text = soup.get_text(separator="", strip=False)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


_AUTHOR_LINE_RE  = re.compile(r"^💬")
_DIVIDER_LINE_RE = re.compile(r"^─+$")

def _clean_line(line: str) -> str:
    if _AUTHOR_LINE_RE.match(line):
        return line
    if _DIVIDER_LINE_RE.match(line):
        return line
    if "▶ Video" in line:
        return line
    line = re.sub(r"https?://\S+", "", line)
    line = re.sub(r"@\w+", "", line)
    # Do NOT strip #hashtags here — trailing hashtag blocks are already
    # removed by _process_p_tags() before html_to_text runs.
    # Remaining hashtags are inline (part of the sentence meaning) — keep them.
    line = re.sub(r"[ \t]+", " ", line).strip()
    return line

def clean_text(raw: str) -> str:
    if not raw:
        return ""
    text = re.sub(r"^R(?:T\s+by|(?:\s+to))\s+@\w+:\s*",
                  "", raw.strip(), flags=re.IGNORECASE)
    lines   = text.split("\n")
    cleaned = [_clean_line(line) for line in lines]
    result_lines: list[str] = []
    blank_count = 0
    for line in cleaned:
        if line == "":
            blank_count += 1
            if blank_count <= 1:
                result_lines.append("")
        else:
            blank_count = 0
            result_lines.append(line)
    text = "\n".join(result_lines).strip()
    if len(text) > MAX_TEXT_LEN:
        text = text[:MAX_TEXT_LEN].rsplit(" ", 1)[0] + "…"
    return text

def clean_title(raw: str) -> str:
    if not raw:
        return ""
    text = " ".join(raw.split())
    text = re.sub(r"^R(?:T\s+by|(?:\s+to))\s+@\w+:\s*",
                  "", text, flags=re.IGNORECASE)
    text = re.sub(r"https?://\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > 200:
        text = text[:200].rsplit(" ", 1)[0] + "…"
    return text

# ─────────────────────────────────────────────────────────────────────────────
# Image extraction
# ─────────────────────────────────────────────────────────────────────────────

def extract_images(html: str, base_url: str = "") -> list[str]:
    if not html:
        return []
    soup = BeautifulSoup(html, "html.parser")
    seen:   set[str]  = set()
    images: list[str] = []
    for img in soup.find_all("img"):
        src = (img.get("data-src") or img.get("src") or "").strip()
        if not src:
            continue
        if src.startswith("//"):
            src = "https:" + src
        elif not src.startswith("http") and base_url:
            src = urljoin(base_url, src)
        if not src.startswith("http") or IGNORED_IMAGE_RE.search(src):
            continue
        if src not in seen:
            seen.add(src); images.append(src)
    return images

# ─────────────────────────────────────────────────────────────────────────────
# Entry processor
# ─────────────────────────────────────────────────────────────────────────────

def process_entry(entry: feedparser.FeedParserDict, feed_url: str) -> dict:
    raw_html = ""
    if getattr(entry, "content", None):
        raw_html = entry.content[0].get("value", "")
    if not raw_html:
        raw_html = getattr(entry, "summary", "")

    parsed_url = urlparse(feed_url)
    base_url   = f"{parsed_url.scheme}://{parsed_url.netloc}"

    html_desc = clean_html(raw_html, base_url=base_url)
    text_desc = clean_text(html_to_text(raw_html))

    images: list[str] = extract_images(raw_html, base_url=base_url)
    seen = set(images)
    for mc in getattr(entry, "media_content", []):
        url = mc.get("url", "").strip()
        if url and url not in seen and not IGNORED_IMAGE_RE.search(url):
            seen.add(url); images.append(url)
    for enc in getattr(entry, "enclosures", []):
        url = enc.get("url", "").strip()
        if url and url not in seen and not IGNORED_IMAGE_RE.search(url):
            seen.add(url); images.append(url)

    title    = clean_title(getattr(entry, "title", "") or "")
    link     = getattr(entry, "link",  "") or ""
    guid     = getattr(entry, "id",   link) or link
    pub_date = ""
    pp = getattr(entry, "published_parsed", None)
    if pp:
        dt = datetime(*pp[:6], tzinfo=timezone.utc)
        pub_date = dt.strftime("%a, %d %b %Y %H:%M:%S +0000")

    return {
        "title":    title or "(no title)",
        "link":     link,
        "guid":     guid,
        "pub_date": pub_date,
        "html":     html_desc,
        "text":     text_desc,
        "images":   images,
    }

# ─────────────────────────────────────────────────────────────────────────────
# RSS 2.0 builder
# ─────────────────────────────────────────────────────────────────────────────

def _xe(s: str) -> str:
    return escape(s, {'"': "&quot;"})

def build_rss(feed_title: str, feed_link: str, feed_desc: str,
              items: list[dict], mode: str = "html") -> str:
    item_blocks: list[str] = []
    for item in items:
        images       = item["images"]
        desc_content = item["html"] if mode == "html" else item["text"]
        if images:
            enc_block = "\n    " + "\n    ".join(
                f'<enclosure url="{_xe(img)}" type="image/jpeg" length="0"/>'
                for img in images
            )
        else:
            enc_block = ""
        item_blocks.append(
            f"""  <item>
    <title><![CDATA[{item['title']}]]></title>
    <link>{_xe(item['link'])}</link>
    <guid isPermaLink="false">{_xe(item['guid'])}</guid>
    <pubDate>{item['pub_date']}</pubDate>
    <description><![CDATA[{desc_content}]]></description>{enc_block}
  </item>"""
        )
    now       = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
    items_xml = "\n".join(item_blocks)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
<channel>
  <title><![CDATA[{feed_title}]]></title>
  <link>{_xe(feed_link)}</link>
  <description><![CDATA[{feed_desc}]]></description>
  <lastBuildDate>{now}</lastBuildDate>
{items_xml}
</channel>
</rss>"""

# ─────────────────────────────────────────────────────────────────────────────
# Flask application
# ─────────────────────────────────────────────────────────────────────────────
app = Flask(__name__)

@app.route("/clean")
def clean_feed():
    url = request.args.get("url",    "").strip()
    fmt = request.args.get("format", "html").strip().lower()
    if not url:
        return jsonify(error="Missing 'url' query parameter."), 400
    if fmt not in ("html", "text"):
        return jsonify(error="'format' must be 'html' or 'text'."), 400
    if not is_url_allowed(url):
        log.warning("Blocked: %s", url)
        return jsonify(error="URL not in whitelist."), 403

    cache_key = hashlib.md5(f"{url}|{fmt}".encode()).hexdigest()
    if cached := cache_get(cache_key):
        return Response(cached, mimetype="application/rss+xml")

    log.info("Fetching [%s]: %s", fmt, url)
    feed = fetch_feed(url)
    if feed is None:
        return jsonify(error="Failed to fetch or parse the feed."), 502

    entries   = feed.entries[:MAX_ITEMS]
    processed = [process_entry(e, url) for e in entries]
    processed.sort(key=lambda x: x["pub_date"] or "", reverse=True)

    feed_desc = clean_feed_description(
        getattr(feed.feed, "description", "Cleaned RSS feed"))

    rss_out = build_rss(
        feed_title=getattr(feed.feed, "title", "Cleaned Feed"),
        feed_link =getattr(feed.feed, "link",  url),
        feed_desc =feed_desc,
        items=processed,
        mode=fmt,
    )
    cache_set(cache_key, rss_out)
    return Response(rss_out, mimetype="application/rss+xml")


@app.route("/clean-all")
def clean_all_feeds():
    raw_urls = request.args.get("urls",   "").strip()
    fmt      = request.args.get("format", "html").strip().lower()
    if not raw_urls:
        return jsonify(error="Missing 'urls' query parameter."), 400
    if fmt not in ("html", "text"):
        return jsonify(error="'format' must be 'html' or 'text'."), 400
    urls = [u.strip() for u in raw_urls.split(",") if u.strip()]
    if not urls:
        return jsonify(error="No valid URLs provided."), 400
    blocked = [u for u in urls if not is_url_allowed(u)]
    if blocked:
        return jsonify(error="Some URLs not in whitelist.", blocked=blocked), 403

    combo_key = hashlib.md5(("|".join(sorted(urls)) + "|" + fmt).encode()).hexdigest()
    if cached := cache_get(combo_key):
        return Response(cached, mimetype="application/rss+xml")

    all_items:  list[dict] = []
    seen_guids: set[str]   = set()
    for url in urls:
        feed = fetch_feed(url)
        if feed is None:
            log.warning("Skipping: %s", url)
            continue
        for entry in feed.entries[:MAX_ITEMS]:
            item = process_entry(entry, url)
            if item["guid"] in seen_guids:
                continue
            seen_guids.add(item["guid"])
            all_items.append(item)

    all_items.sort(key=lambda x: x["pub_date"] or "", reverse=True)
    rss_out = build_rss("Combined Cleaned Feed", "",
                        f"Merged from {len(urls)} Nitter feed(s)",
                        all_items, mode=fmt)
    cache_set(combo_key, rss_out)
    return Response(rss_out, mimetype="application/rss+xml")


@app.route("/health")
def health():
    return jsonify(status="ok", cached_feeds=len(_cache)), 200

@app.route("/")
def index():
    return jsonify(
        endpoints={
            "GET /clean":     "?url=<rss_url>[&format=html|text]",
            "GET /clean-all": "?urls=<url1>,<url2>,…[&format=html|text]",
            "GET /health":    "health check",
        },
        format_modes={
            "html": "DEFAULT — keeps HTML, best for RSStT bot",
            "text": "plain text, best for simple RSS bots",
        },
        note="Only whitelisted Nitter RSS domains accepted.",
    )

if __name__ == "__main__":
    app.run(debug=True, port=5000)
